#!/bin/bash

savePath="/Volumes/MediaStripe/"
echo what is your filename?
read varinput

filename="${varinput##*/}"
testfilename="${filename%.*}"

echo what is your start 'time'?
read setStart

echo what is your end 'time'?
read setEnd


ffmpeg -i $varinput -ss $setStart -to $setEnd -map v:0 -map a:0 -c:v libx264 -profile:v main -level 3.1 -pix_fmt yuv420p -s 1280x720 -crf 18 -maxrate 4000000 -bufsize 4000001 -c:a aac -b:a 128k -ar 44100 -af loudnorm=-16:8:-1 -movflags +faststart $savePath$testfilename.mp4